a=input("enter the word:")
print("capitalise:",a.capitalize())
print("swap the case",a.swapcase())
print("check is lower",a.islower())
print("max is",max(a))
print("min is",min(a))
print("check i supper:",a.isupper())
print("len is",len(a))
print("center",a.center(60))
e=input("enter the value to count")
print("count of",e+"is",a.count(e))